MovieShop.MVC/Models/ErrorViewModel.cs
using System;

namespace MovieShop.MVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MovieShop.MVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MovieShop.MVC.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using ApplicationCore.ServiceInterfaces;
using Infrastructure.Services;

namespace MovieShop.MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        private readonly IMovieService _movieService;



        public HomeController(IMovieService movieService, ILogger<HomeController> logger)
        {
            _logger = logger;
            _movieService = movieService;
        }


        //[MovieShopHeaderFilter]
        //will go to filter folder and execute that class
        public async Task<IActionResult> Index()
        {
            _logger.LogInformation("Logging non critcial inforamtion {dateTime}", DateTime.UtcNow);

            //try
            //{
            //    throw new Exception("my custom exception");
            //}
            //catch (Exception e)
            //{
            //    _logger.LogError("caught exception{dateTime}",DateTime.UtcNow);
            //}

            var movies = await _movieService.Get30HighestGrossing();
            return View(movies);
        }

        public IActionResult Privacy()
        {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MovieShop.MVC/Controllers/MoviesController.cs
using Infrastructure.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ApplicationCore.Models.Request;
using ApplicationCore.ServiceInterfaces;
using ApplicationCore.Models.Response;

namespace MovieShop.MVC.Controllers
{
    public class MoviesController : Controller
    {
        // private MovieService _movieService;
        private readonly IMovieService _movieService;
        //When you programing is running , the IMovieService is repalced by implementation
        private readonly ICastService _castService;

        private readonly IGenreService _genreService;


        public MoviesController(IMovieService movieService, ICastService castService, IGenreService genreService)
        {
            // 1.Constructir injection***** inject the implemenation into the 
            //constructor of the class
            //_movieService = new MovieService();
            _movieService = movieService;
            _castService = castService;
            _genreService = genreService;
        }

        public async Task<IActionResult> Index()
        {
            //private MovieService _movieService;
            //It will look for a veiw with name called index(becasue the action method name is index )
            //return index2, TestView
            // 1.ViewBag - built in MVC  
            //2.ViewData - built in MVC
            //3.Strongly typed models ****
            //send list of top 30 movies to teh view 
            //id, title, posterlurl
            // ViewBag.PageTitle = "Top 30 Grosiing Movies";
            var movies = await _movieService.Get30HighestGrossing();
            return View(movies);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            //_movieService.
            // should call Movie Service to get the details of the Movie that includes Movie Details, Cast for that Movie, Rating for that Movie
            var movie = await _movieService.GetMovieDetailsAsync(id);
            return View(movie);
        }


        [HttpGet]
        public async Task<IActionResult> CastDetails(int id)
        {
            var cast = await _castService.GetCastAsync(id);
            return View(cast);
        }


        [HttpGet]
        public async Task<IActionResult> GenreDetails(int Id)
        {
            var movies = await _movieService.GetAllMovies(Id);
            return View(movies);
        }



        //we want to show blank page with all the inputs
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        //receive Movie information from View then submitted 
        public IActionResult Create(MovieCreateRequestModel model)
        {
            _movieService.CreateMovie(model);
            return RedirectToAction("Index");
        }

    }
}

MovieShop.MVC/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;

namespace MovieShop.MVC.Controllers
{
    public class UserController : Controller
    {

        //This attribute used cookies based authication in configruservice
        // it will check the cookie to see user is login or not 

        [Authorize]  // this will check the IsAutheticated in identity hettpcontxt in auto whichi is cookies 
        [HttpGet]
        public async Task<IActionResult> GetUserPurchasedMovies()
        {
            //call user service by id for user to get all movies he/she purchased
            return View();
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> PurchaseMovie()
        {
            return View();
        }

    }
}

MovieShop.MVC/Views/Shared/Components/Genres/GenresViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Infrastructure.Services;
using ApplicationCore.ServiceInterfaces;
namespace MovieShop.MVC.Views.Components.Genres
{
    public class GenresViewComponent : ViewComponent
    {
        private readonly IGenreService _genreService;

        public GenresViewComponent(IGenreService genreService)
        {
            _genreService = genreService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var genres = await _genreService.GetAllGenres();
            return View(genres);
        }

        //[HttpGet]
        //public async Task<IActionResult> GenreDetails(string name)
        //{
        //    var movies = await _genreService.GetAllMovies(name);
        //    return View(movies);
        //}




    }
}

MovieShop.MVC/Views/Home/Index.cshtml
@model IEnumerable<ApplicationCore.Models.Response.MovieCardResponseModel>


@{ ViewData["Title"] = "Home Page"; }

<div class="rounded">
    <div class="container-fluid bg-light">
        <div class="row">
            @foreach (var movie in Model)
            {
                <div class="col-6 col-lg-3 col-sm-4 col-xl-2">
                     @await Html.PartialAsync("_MovieCard", movie)
                </div>}
        </div>
    </div>
</div>

MovieShop.MVC/Views/Movies/CastDetails.cshtml
@model ApplicationCore.Models.Response.CastDetailsResponseModel

<div class="container">
    <div class="row">
        <div class="col">
            <div>

                <p>@Model.Name</p>
                <p>
                    <img src="@Model.ProfilePath"
                         class="rounded float-start"
                         alt="@Model.Name" />
                </p>
                <h5>Movie List</h5>
                @foreach (var movie in Model.Movie)
                {
                    <p>
                        <img src="@movie.PosterUrl"
                             class="rounded float-start"
                             alt="@movie.PosterUrl" />
                    </p>

                }



            </div>
        </div>
        <div class="col-6">
            2 of 3 (wider)
        </div>
        <div class="col">
            3 of 3
        </div>
    </div>
    <div class="row">
        <div class="col">
            1 of 3
        </div>
        <div class="col-5">
            2 of 3 (wider)
        </div>
        <div class="col">
            3 of 3
        </div>
    </div>
</div>

MovieShop.MVC/Views/Movies/Create.cshtml
@model ApplicationCore.Models.Request.MovieCreateRequestModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>MovieCreateRequestModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Overview" class="control-label"></label>
                <input asp-for="Overview" class="form-control" />
                <span asp-validation-for="Overview" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Budget" class="control-label"></label>
                <input asp-for="Budget" class="form-control" />
                <span asp-validation-for="Budget" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MovieShop.MVC/Views/Movies/Details.cshtml
@model ApplicationCore.Models.Response.MovieDetailsResponseModel


<div class="container">
    <div class="row">
        <div class="col">
            <img src="@Model.PosterUrl "
                 class="rounded float-start"
                 alt="@Model.Title" />
        </div>

        <div class="col-6">
            <div>
                <p>@Model.Title</p>
            </div>
            <div>
                @foreach (var g in Model.Genre)

                {
                    <span class="badge bg-warning text-dark">@g.Name</span>
                }

            </div>

            <div>
                <span class="badge bg-warning text-dark">@Model.Rating</span>
            </div>
            <div>
                <p>@Model.Overview</p>
            </div>
        </div>

        <div class="col">
            3 of 3
        </div>
    </div>
    <div class="row">
        <div class="col">
            <h5>MOVIE FACTS</h5>
            <table class="table table-striped">
                <tbody>
                    <tr>
                        <td> Release Date   </td>

                        <td><span class="badge bg-dark text-white">@Model.ReleaseDate</span></td>
                    </tr>
                    <tr>
                        <td> Run Time   </td>
                        <td><span class="badge bg-dark text-white">@Model.RunTime</span></td>
                    </tr>
                    <tr>
                        <td> Box Office   </td>
                        <td><span class="badge bg-dark text-white">@Model.Revenue </span></td>
                    </tr>
                    <tr>
                        <td> Budget   </td>
                        <td><span class="badge bg-dark text-white">@Model.Budget</span></td>
                    </tr>
                </tbody>
            </table>

        </div>
        <div class="col-5">
            <h5>CAST</h5>
            <table class="table">
                <tbody>
                    @foreach (var cast in Model.Casts)
                    {
                        <tr>
                            <td>
                                <a asp-controller="Movies" asp-action="CastDetails" asp-route-id="@cast.Id">
                                    <img src="@cast.ProfilePath "
                                         class="rounded float-start"
                                         alt="@cast.Name" />
                                </a>
                            </td>
                            <td> @cast.Name </td>
                            <td> @cast.Character</td>
                        </tr>

                    }
                </tbody>
            </table>
        </div>
        <div class="col">
            3 of 3
        </div>
    </div>
</div>




MovieShop.MVC/Views/Movies/GenreDetails.cshtml
@model List<ApplicationCore.Models.Response.MovieCardResponseModel>


<h5>Movie List: </h5>
@foreach (var movie in Model)
{
    <p>
        <img src="@movie.PosterUrl"
             class="rounded float-start"
             alt="@movie.PosterUrl" />
    </p>

}

MovieShop.MVC/Views/Movies/Index.cshtml
@model List<ApplicationCore.Models.Response.MovieCardResponseModel>

<h2>
    @ViewBag.PageTitle
</h2>

<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Title</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var movie in Model)
        {
            <tr>
                <td>@movie.Id</td>
                <td>@movie.Title</td>
            </tr>
        }
    </tbody>
</table>

MovieShop.MVC/Views/Movies/TestView.cshtml
<h2>
    Test View clled from index action
</h2>

MovieShop.MVC/Views/Shared/Components/Genres/Default.cshtml
@model IEnumerable<ApplicationCore.Models.Response.GenreModel>


@foreach (var genre in Model)
{ //alias of GenreModel
    <a class="dropdown-item" asp-action="GenreDetails" asp-controller="Movies" asp-route-id="@genre.Id">@genre.Name</a>
}

MovieShop.MVC/Views/Shared/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

MovieShop.MVC/Views/Shared/_CastCard.cshtml
@model ApplicationCore.Models.Response.CastDetailsResponseModel

<div class="card mb-4 shadow bg-light">
    <a asp-controller="Movies" asp-action="CastDetails" asp-route-id="@Model.Id">
    </a>
</div>

MovieShop.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieShop.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">

            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"> Movie   Shop </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item dropdown">
                        <a class="nav-link text-dark dropdown-toggle" href="#" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Genres</a>
                        <div class="dropdown-menu">
                            @await Component.InvokeAsync("Genres")
                        </div>
                    </li>
                </ul>
            </div>


            <partial name="_LoginInfoPartial" />


        </nav>
    </header>
    <div class="container-fluid mt-1">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MovieShop.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MovieShop.MVC/Views/Shared/_LoginInfoPartial.cshtml
@using ApplicationCore.ServiceInterfaces;

@inject ICurrentUserService _currentUserService

@if (User.Identity.IsAuthenticated)
{
    <div class="navbar-collapse collapse w-100 order-3">
        <ul class="navbar-nav ml-auto">



            @if (_currentUserService.IsAdmin || _currentUserService.IsSuperAdmin)
            {
                <li class="nav-item dropdown text-capitalize">
                    <a class="nav-link dropdown-toggle" id="dropdown01" data-toggle="dropdown"
                       style="cursor: pointer;" aria-haspopup="true"
                       aria-expanded="false">
                        Admin
                    </a>
                    <div class="dropdown-menu" aria-labelledby="dropdown01">
                        <a class="dropdown-item" asp-controller="Admin" asp-action="CreateMovie">Create Movie</a>
                        <a class="dropdown-item" asp-controller="Admin" asp-action="CreateCast">Create Cast</a>
                        <a class="dropdown-item" asp-controller="Admin" asp-action="Index">Home</a>
                    </div>
                </li>
            }



            <li class="nav-item dropdown text-capitalize">
                <a class="nav-link dropdown-toggle" id="dropdown01" data-toggle="dropdown"
                   style="cursor: pointer;" aria-haspopup="true"
                   aria-expanded="false">
                    @_currentUserService.FullName
                </a>



                <div class="dropdown-menu" aria-labelledby="dropdown01">
                    <a class="dropdown-item">Library</a>
                    <a class="dropdown-item" asp-controller="Account" asp-action="Logout">Log Out</a>
                    <a class="dropdown-item" asp-controller="Account" asp-action="Profile">View Profile</a>
                    <a class="dropdown-item" asp-controller="Account" asp-action="EditProfile">Edit Profile</a>
                </div>
            </li>
        </ul>
    </div> }



else
{
    <div class="navbar-collapse collapse w-100 order-3">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item pr-4">
                <a class="btn btn-outline-primary" asp-controller="Account" asp-action="Login">Login</a>
            </li>
            <li class="nav-item">
                <a class="btn btn-outline-primary" asp-controller="Account" asp-action="Register">Register</a>
            </li>
        </ul>



    </div>}

MovieShop.MVC/Views/Shared/_MovieCard.cshtml
@model ApplicationCore.Models.Response.MovieCardResponseModel

<div class="card mb-4 shadow bg-light">
    <a asp-controller="Movies" asp-action="Details" asp-route-id="@Model.Id">
        <img src="@Model.PosterUrl" class="img-fluid" alt="@Model.Title" />
    </a>
</div>